choco install 7zip -y
choco install filezilla -y
choco install audacity -y
choco install skype -y
choco install cpu-z -y
choco install vmwareworkstation -y
choco install firefox -y
choco install brave -y
choco install minecraft-launcher -y
choco install googlechrome -y
choco install vscode -y
choco install notepadplusplus -y
choco install vlc -y
choco install putty -y
choco install git -y
choco install docker-desktop -y
choco install docker-cli -y
choco install docker-engine -y
choco install office-tool -y
choco install thunderbird -y
choco install bitwarden -y
choco install gpg4win -y
choco install signal -y
choco install geforce-experience -y
choco install steam -y
choco install ubisoft-connect -y
choco install epicgameslauncher -y
choco install origin -y
choco install amazongames -y
choco install goggalaxy -y
choco install plexmediaplayer -y
choco install plexmediaserver -y
choco install discord -y
choco install filebot -y
choco install geekuninstaller -y
choco install exif-purge -y
choco install exiftool -y
choco install itunes -y
choco install zoom -y
choco install ea-app -y
choco install legacy-games-launcher -y
choco install rockstar-launcher -y
choco install anydesk -y
choco install coretemp -y
choco install hwinfo -y
choco install humble-app -y
choco install qbittorrent -y
choco install winscp -y
choco install icloud -y
choco install cryptomator -y
choco install github-desktop -y
choco install sublimetext3 -y
choco install sublimetext4 -y
choco install putty.install -y
choco install vim -y
choco install nano -y
choco install rainmeter -y
choco install obs -y
choco install handbrake -y
choco install calibre -y
choco install chirp -y
choco install hexchat -y
choco install ledger-live -y
choco install renamemytvseries2 -y
